version: "3.9"

services:
  app:
    container_name: echo
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./configs:/app/configs
    depends_on:
      - liquibase


  next:
    container_name: echo2
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - pg
  
  liquibase:
    container_name: db_updater
    image: liquibase/liquibase:4.7.0
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://pg:5432/docker" --changeLogFile=./changelog/changelog.xml --username=root --password=password update
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
