version: "3.9"

services:
  app:
    container_name: echo
    build: .
    environment:
      KAFKA_BROKER: "broker:29092"
    ports:
      - 9999:9999
    volumes:
      - ./configs:/app/configs
    depends_on:
      - liquibase_pg
      - broker
    restart: always

  next:
    container_name: beta
    build: .
    ports:
      - 8888:8888
    depends_on:
      - liquibase_maria
    environment:
      DB_HOST: maria
      DB_PORT: 3306
      DB_USER: docker
      DB_PASSWORD: password
      DB_NAME: docker
      DB_TYPE: MARIA
      APP_PORT: 8888
      TARGET: "http://echo:9999"
      ERROR_RATE: 10
      DELAY: 3000
    restart: always


  liquibase_pg:
    container_name: pg_updater
    image: liquibase/liquibase:4.7.0
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://pg:5432/docker" --changeLogFile=./changelog/changelog.xml --username=root --password=password update
    depends_on:
      - pg

  
  liquibase_maria:
    container_name: mariadb_updater
    image: liquibase/liquibase:4.7.0
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:mariadb://maria:3306/docker" --changeLogFile=./changelog/changelog.xml --username=docker --password=password  update
    depends_on:
      - maria

  pg:
    container_name: pg
    image: postgres:13.1
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  
  maria:
    container_name: maria
    image: mariadb:10.7
    healthcheck:
      test: mysqladmin ping 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      timeout: 45s
      interval: 10s
      retries: 10
      start_period: 20s
    restart: always
    environment:
      MARIADB_USER: docker
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: docker
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./maria:/var/lib/mysql
    ports:
      - 3306:3306

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1