{
 "title": "HTTP Services",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_request_duration_seconds_sum, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\", instance=\"$instance\"}[5m]))",
     "legendFormat": "$instance"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\", instance=\"$instance\"}[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\", status_code=~\"5..\", instance=\"$instance\"}[5m]))",
     "legendFormat": "$instance"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\", status_code=~\"5..\", instance=\"$instance\"}[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"apps\", instance=\"$instance\"}[5m])))",
     "legendFormat": "$instance"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(http_request_duration_seconds_bucket{job=\"apps\", instance=\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(http_concurrent_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "Overiew", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"apps\", status_code=~\"5..\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, instance) (rate(http_request_duration_seconds_bucket{job=\"apps\"}[5m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(http_concurrent_requests{}[5m]) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}