{
 "title": "The USE method",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total[5m])) + sum(rate(node_network_transmit_drop_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "  sum(rate(node_network_transmit_errs_total[5m]))\n/ \n  sum(rate(node_network_transmit_packets_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Saturation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "1e3 * sum(node_load1{job=\"prometheus\"})/sum(node:node_num_cpu:sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "1 - avg(rate(node_cpu_seconds_total{job=\"prometheus\",mode=\"idle\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "1e3 * sum(rate(node_vmstat_pgpgin{job=\"prometheus\"}[1m]) +rate(node_vmstat_pgpgout{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemFree_bytes{job=\"prometheus\"}+node_memory_Cached_bytes{job=\"prometheus\"}+node_memory_Buffers_bytes{job=\"prometheus\"})/sum(node_memory_MemTotal_bytes{job=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}