APP_PORT=8888
DB_HOST="pg"
DB_PORT=5432
DB_USER="root"
DB_PASSWORD="password"
DB_NAME="docker"
DB_TYPE="PG"
TARGET="http://echo:9999"
ERROR_RATE=60
DELAY=5000
# DB_HOST="localhost"
# DB_PORT=3306
# DB_USER="docker"
# DB_PASSWORD="password"
# DB_NAME="docker"
# DB_TYPE="MARIA"